#!/bin/bash

if [ $# != 1 ]
then
	echo " Takes the form \" ./backlight [1|0] \" "
	echo " Where 1 is on and 0 is off"
	exit
elif  (( ($1 != "1")  && ($1 != "0") )) 
then
	echo " Takes the form \" ./backlight [1|0] \" "
	echo " Where 1 is on and 0 is off"
	exit
fi
sudo sh -c "echo 252 > /sys/class/gpio/export"
#ls -l /sys/class/gpio
sudo sh -c "echo 'out' > /sys/class/gpio/gpio252/direction"
sudo sh -c "echo '$1' > /sys/class/gpio/gpio252/value"


